"""Locate and load the contracts' build artifacts (ABI, bytecode, addresses).

ABIs come from `contracts/out/` — regenerated by forge, never copy-pasted (docs/01
M1.5 "watch for"). Addresses come from `contracts/deployments/anvil.json`, the deploy
script's artifact (docs/03 §2.4). This module is pure file reading; no chain I/O.
"""

from __future__ import annotations

import json
from pathlib import Path

from eth_utils import keccak


def find_contracts_dir(start: Path | None = None) -> Path:
    """Walk up from `start` (default: this file) to the repo root's contracts/ dir.

    Lets any working directory — pytest, a notebook, an MCP server — find the
    artifacts without configuration. Explicit paths still win everywhere: this is
    only the default.
    """
    here = start or Path(__file__).resolve()
    for parent in [here, *here.parents]:
        candidate = parent / "contracts"
        if (candidate / "foundry.toml").exists():
            return candidate
    raise FileNotFoundError("no contracts/ directory with a foundry.toml above " + str(here))


def _artifact(contract_name: str, contracts_dir: Path | None) -> dict:
    contracts = contracts_dir or find_contracts_dir()
    # forge lays artifacts out as out/<SourceFile>.sol/<ContractName>.json, and the
    # source file need not share the contract's name (A2ASettlement ← Settlement.sol).
    matches = sorted((contracts / "out").glob(f"*.sol/{contract_name}.json"))
    if not matches:
        raise FileNotFoundError(
            f"no forge artifact for {contract_name} under {contracts / 'out'} — run forge build"
        )
    return json.loads(matches[0].read_text())


def load_abi(contract_name: str, contracts_dir: Path | None = None) -> list[dict]:
    return _artifact(contract_name, contracts_dir)["abi"]


def load_bytecode(contract_name: str, contracts_dir: Path | None = None) -> str:
    return _artifact(contract_name, contracts_dir)["bytecode"]["object"]


def load_deployment(contracts_dir: Path | None = None) -> dict:
    """The `just deploy-local` artifact: {"v", "chainId", "MockTOK", "A2ASettlement"}."""
    contracts = contracts_dir or find_contracts_dir()
    return json.loads((contracts / "deployments" / "anvil.json").read_text())


def error_selectors(*abis: list[dict]) -> dict[bytes, str]:
    """4-byte selector → custom-error name, for decoding reverts.

    Built from the ABIs themselves so it automatically covers our errors AND the
    inherited OpenZeppelin ones (ERC20InsufficientAllowance, ERC721NonexistentToken…).
    """
    table: dict[bytes, str] = {}
    for abi in abis:
        for entry in abi:
            if entry.get("type") != "error":
                continue
            signature = entry["name"] + "(" + ",".join(i["type"] for i in entry["inputs"]) + ")"
            table[keccak(text=signature)[:4]] = entry["name"]
    return table
